apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: node-specific-sizing
  name: node-specific-sizing
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-specific-sizing
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: node-specific-sizing
  name: node-specific-sizing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-specific-sizing
subjects:
- kind: ServiceAccount
  name: node-specific-sizing
  namespace: kube-system
---
apiVersion: v1
kind: Endpoints
metadata:
  name: node-specific-sizing
  namespace: kube-system
subsets:
- addresses:
  - ip: 172.19.0.1
  ports:
  - port: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: node-specific-sizing
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-specific-sizing
  name: node-specific-sizing
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-specific-sizing
  template:
    metadata:
      labels:
        app: node-specific-sizing
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: node-specific-sizing:latest
        imagePullPolicy: IfNotPresent
        name: node-specific-sizing
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: node-specific-sizing
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: node-specific-sizing-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root
  namespace: kube-system
spec:
  commonName: ca-root
  isCA: true
  issuerRef:
    kind: Issuer
    name: ca-bootstrap
  privateKey:
    algorithm: RSA
    size: 2048
  secretName: ca-root
  subject:
    countries:
    - FR
    organizations:
    - ManoMano Internal
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: node-specific-sizing-client-cert
  namespace: kube-system
spec:
  commonName: api-server-client-cert-for-node-specific-sizing.manomano.tech
  duration: 2160h
  isCA: false
  issuerRef:
    kind: Issuer
    name: ca-root
  privateKey:
    algorithm: RSA
    size: 2048
  renewBefore: 360h
  secretName: client-cert
  usages:
  - client auth
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: kubernetes-node-specific-sizing
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: kubernetes-node-specific-sizing
  name: node-specific-sizing-serving-cert
  namespace: kube-system
spec:
  dnsNames:
  - node-specific-sizing.kube-system.svc
  - node-specific-sizing.kube-system.svc.cluster.local
  duration: 2160h
  isCA: false
  issuerRef:
    kind: Issuer
    name: ca-root
  privateKey:
    algorithm: RSA
    size: 2048
  renewBefore: 360h
  secretName: node-specific-sizing-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-bootstrap
  namespace: kube-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-root
  namespace: kube-system
spec:
  ca:
    secretName: ca-root
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-system/node-specific-sizing-client-cert
  name: node-specific-sizing
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: node-specific-sizing
      namespace: kube-system
      path: /mutate
  failurePolicy: Ignore
  name: node-specific-sizing.svc.cluster.local
  objectSelector:
    matchLabels:
      node-specific-sizing.manomano.tech/enabled: "true"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 2
