{{- if and .Values.rbac.create (or (not .Values.rbac.namespaced) .Values.rbac.extraClusterRoleRules) (not .Values.rbac.useExistingClusterRole) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: 
    {{ - include "node-specific-sizing.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "node-specific-sizing.fullname" . }}-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
    {{- with .Values.rbac.extraClusterRoleRules }}
    {{- toYaml . | nindent 2 }}
    {{- end}}
{{- end }}